name: Trigger Cypress Tests with Logs

on:
  workflow_dispatch:
    inputs:
      project:
        description: "Select the project to run"
        required: true
        type: choice
        options:
          - awsCypress-main1
          - awsCypress-main2

jobs:
  trigger-selected-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Log: Start of Workflow
        run: echo -e "\e[34m🔵 [INFO] Starting the workflow...\e[0m"

      - name: Log: Selected Project
        run: echo -e "\e[32m🟢 [SUCCESS] Selected project: ${{ github.event.inputs.project }}\e[0m"

      - name: Trigger Cypress Tests for awsCypress-main1
        if: ${{ github.event.inputs.project == 'awsCypress-main1' }}
        run: |
          echo -e "\e[33m🟡 [INFO] Triggering workflow for awsCypress-main1...\e[0m"
          gh workflow run cypress.yml --repo ${{ github.repository }} --ref main --inputs project=awsCypress-main1
          if [ $? -eq 0 ]; then
            echo -e "\e[32m✅ [SUCCESS] Successfully triggered awsCypress-main1 workflow!\e[0m"
          else
            echo -e "\e[31m❌ [ERROR] Failed to trigger awsCypress-main1 workflow.\e[0m"
            exit 1
          fi

      - name: Trigger Cypress Tests for awsCypress-main2
        if: ${{ github.event.inputs.project == 'awsCypress-main2' }}
        run: |
          echo -e "\e[33m🟡 [INFO] Triggering workflow for awsCypress-main2...\e[0m"
          gh workflow run cypress.yml --repo ${{ github.repository }} --ref main --inputs project=awsCypress-main2
          if [ $? -eq 0 ]; then
            echo -e "\e[32m✅ [SUCCESS] Successfully triggered awsCypress-main2 workflow!\e[0m"
          else
            echo -e "\e[31m❌ [ERROR] Failed to trigger awsCypress-main2 workflow.\e[0m"
            exit 1
          fi

      - name: Log: End of Workflow
        run: echo -e "\e[34m🔵 [INFO] Workflow execution complete.\e[0m"
